/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : bigint,
  'bio' : string,
  'clanId' : [] | [bigint],
  'episodes' : Array<bigint>,
  'name' : string,
  'role' : string,
}
export interface Clan {
  'id' : bigint,
  'members' : Array<bigint>,
  'name' : string,
  'description' : string,
}
export interface Episode {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'videoUrl' : string,
  'releaseDate' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'creator' : string,
  'date' : bigint,
  'description' : string,
  'imageUrl' : string,
}
export interface NewsPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface Script {
  'id' : bigint,
  'title' : string,
  'creator' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemberToClan' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacter' : ActorMethod<
    [string, string, string, [] | [bigint], Array<bigint>],
    undefined
  >,
  'createClan' : ActorMethod<[string, string], undefined>,
  'createEpisode' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'createGalleryItem' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'createNewsPost' : ActorMethod<[string, string], undefined>,
  'createScript' : ActorMethod<[string, string, string], undefined>,
  'deleteCharacter' : ActorMethod<[bigint], undefined>,
  'deleteClan' : ActorMethod<[bigint], undefined>,
  'deleteEpisode' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNewsPost' : ActorMethod<[bigint], undefined>,
  'deleteScript' : ActorMethod<[bigint], undefined>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getAllClans' : ActorMethod<[], Array<Clan>>,
  'getAllEpisodes' : ActorMethod<[], Array<Episode>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllNewsPosts' : ActorMethod<[], Array<NewsPost>>,
  'getAllScripts' : ActorMethod<[], Array<Script>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacterById' : ActorMethod<[bigint], [] | [Character]>,
  'getClanById' : ActorMethod<[bigint], [] | [Clan]>,
  'getEpisodeById' : ActorMethod<[bigint], [] | [Episode]>,
  'getGalleryImages' : ActorMethod<[], Array<ExternalBlob>>,
  'getGalleryItemById' : ActorMethod<[bigint], [] | [GalleryItem]>,
  'getNewsPostById' : ActorMethod<[bigint], [] | [NewsPost]>,
  'getNewsPostsByAuthor' : ActorMethod<[string], Array<NewsPost>>,
  'getScriptById' : ActorMethod<[bigint], [] | [Script]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantRole' : ActorMethod<[Principal, UserRole], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTeamMembers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'removeMemberFromClan' : ActorMethod<[bigint, bigint], undefined>,
  'revokeRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCharacter' : ActorMethod<
    [bigint, string, string, string, [] | [bigint], Array<bigint>],
    undefined
  >,
  'updateClan' : ActorMethod<[bigint, string, string], undefined>,
  'updateEpisode' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateNewsPost' : ActorMethod<[bigint, string, string], undefined>,
  'updateScript' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];