/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlockType = { 'title' : null } |
  { 'character' : null } |
  { 'data' : null } |
  { 'list' : null } |
  { 'text' : null } |
  { 'section' : null } |
  { 'progress' : null } |
  { 'image' : null } |
  { 'episode' : null };
export interface Character {
  'id' : bigint,
  'bio' : string,
  'clanId' : [] | [bigint],
  'episodes' : Array<bigint>,
  'name' : string,
  'role' : string,
  'portraitUrl' : string,
}
export interface Clan {
  'id' : bigint,
  'members' : Array<bigint>,
  'name' : string,
  'description' : string,
}
export interface Episode {
  'id' : bigint,
  'taggedCharacterIds' : Array<bigint>,
  'writingComplete' : boolean,
  'title' : string,
  'thumbnailUrl' : string,
  'order' : bigint,
  'description' : string,
  'released' : boolean,
  'explicitReleaseDate' : bigint,
  'animationComplete' : boolean,
  'voiceActingComplete' : boolean,
  'storyboardComplete' : boolean,
  'visibility' : Visibility,
  'videoUrl' : string,
  'editingComplete' : boolean,
  'runtime' : [] | [bigint],
}
export type ExternalBlob = Uint8Array;
export interface FanMailMessage {
  'id' : bigint,
  'adminReply' : [] | [string],
  'submittedAt' : bigint,
  'message' : string,
  'senderName' : string,
  'senderEmail' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'taggedCharacterIds' : Array<bigint>,
  'title' : string,
  'creator' : string,
  'featured' : boolean,
  'creditLink' : [] | [string],
  'artworkTitle' : string,
  'date' : bigint,
  'description' : [] | [string],
  'taggedClanIds' : Array<bigint>,
  'imageUrl' : string,
  'viewCount' : bigint,
  'artistName' : string,
  'popularity' : bigint,
}
export interface NewsPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface ProBlockData {
  'id' : string,
  'height' : bigint,
  'title' : string,
  'dataset' : string,
  'content' : string,
  'transparent' : boolean,
  'meta' : [] | [string],
  'createdAt' : bigint,
  'color' : [] | [string],
  'blockType' : BlockType,
  'updatedAt' : bigint,
  'subTitle' : [] | [string],
  'width' : bigint,
  'position' : bigint,
  'episode' : [] | [bigint],
}
export interface Script {
  'id' : bigint,
  'title' : string,
  'creator' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Visibility = { 'scheduled' : null } |
  { 'publicVisibility' : null } |
  { 'draft' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemberToClan' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacter' : ActorMethod<
    [string, string, string, [] | [bigint], Array<bigint>, string],
    undefined
  >,
  'createClan' : ActorMethod<[string, string], undefined>,
  'createEpisode' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      Visibility,
      Array<bigint>,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
  'createGalleryItem' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      string,
      string,
      boolean,
      Array<bigint>,
      Array<bigint>,
    ],
    undefined
  >,
  'createNewsPost' : ActorMethod<[string, string], undefined>,
  'createScript' : ActorMethod<[string, string, string], undefined>,
  'deleteCharacter' : ActorMethod<[bigint], undefined>,
  'deleteClan' : ActorMethod<[bigint], undefined>,
  'deleteEpisode' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNewsPost' : ActorMethod<[bigint], undefined>,
  'deleteProBlock' : ActorMethod<[string], undefined>,
  'deleteScript' : ActorMethod<[bigint], undefined>,
  'filterGalleryItems' : ActorMethod<
    [Array<bigint>, Array<bigint>, boolean, boolean],
    Array<GalleryItem>
  >,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getAllClans' : ActorMethod<[], Array<Clan>>,
  'getAllEpisodes' : ActorMethod<[], Array<Episode>>,
  'getAllFanMail' : ActorMethod<[], Array<FanMailMessage>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllNewsPosts' : ActorMethod<[], Array<NewsPost>>,
  'getAllProBlocks' : ActorMethod<[], Array<ProBlockData>>,
  'getAllScripts' : ActorMethod<[], Array<Script>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacterById' : ActorMethod<[bigint], [] | [Character]>,
  'getClanById' : ActorMethod<[bigint], [] | [Clan]>,
  'getEpisodeById' : ActorMethod<[bigint], [] | [Episode]>,
  'getFanMailById' : ActorMethod<[bigint], [] | [FanMailMessage]>,
  'getGalleryImages' : ActorMethod<[], Array<ExternalBlob>>,
  'getGalleryItemById' : ActorMethod<[bigint], [] | [GalleryItem]>,
  'getNewsPostById' : ActorMethod<[bigint], [] | [NewsPost]>,
  'getNewsPostsByAuthor' : ActorMethod<[string], Array<NewsPost>>,
  'getProPresentation' : ActorMethod<[], string>,
  'getScriptById' : ActorMethod<[bigint], [] | [Script]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantRole' : ActorMethod<[Principal, UserRole], undefined>,
  'incrementGalleryItemViewCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTeamMembers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'removeMemberFromClan' : ActorMethod<[bigint, bigint], undefined>,
  'reorderEpisodes' : ActorMethod<[Array<bigint>], undefined>,
  'reorderProBlocks' : ActorMethod<[Array<string>], undefined>,
  'replyToFanMail' : ActorMethod<[bigint, string], undefined>,
  'revokeRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProBlock' : ActorMethod<[ProBlockData], undefined>,
  'submitFanMail' : ActorMethod<[string, string, string], undefined>,
  'updateCharacter' : ActorMethod<
    [bigint, string, string, string, [] | [bigint], Array<bigint>, string],
    undefined
  >,
  'updateClan' : ActorMethod<[bigint, string, string], undefined>,
  'updateEpisode' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      Visibility,
      Array<bigint>,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      string,
      string,
      boolean,
      Array<bigint>,
      Array<bigint>,
    ],
    undefined
  >,
  'updateNewsPost' : ActorMethod<[bigint, string, string], undefined>,
  'updateProBlock' : ActorMethod<[string, ProBlockData], undefined>,
  'updateProPresentation' : ActorMethod<[string], undefined>,
  'updateScript' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];