/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Visibility = IDL.Variant({
  'scheduled' : IDL.Null,
  'publicVisibility' : IDL.Null,
  'draft' : IDL.Null,
});
export const Character = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'clanId' : IDL.Opt(IDL.Nat),
  'episodes' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Clan = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Episode = IDL.Record({
  'id' : IDL.Nat,
  'taggedCharacterIds' : IDL.Vec(IDL.Nat),
  'writingComplete' : IDL.Bool,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'released' : IDL.Bool,
  'explicitReleaseDate' : IDL.Int,
  'animationComplete' : IDL.Bool,
  'voiceActingComplete' : IDL.Bool,
  'storyboardComplete' : IDL.Bool,
  'visibility' : Visibility,
  'videoUrl' : IDL.Text,
  'editingComplete' : IDL.Bool,
  'runtime' : IDL.Opt(IDL.Nat),
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const NewsPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Script = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemberToClan' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCharacter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'createClan' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createEpisode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Nat),
        Visibility,
        IDL.Vec(IDL.Nat),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'createGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createNewsPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createScript' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
  'deleteClan' : IDL.Func([IDL.Nat], [], []),
  'deleteEpisode' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteNewsPost' : IDL.Func([IDL.Nat], [], []),
  'deleteScript' : IDL.Func([IDL.Nat], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getAllClans' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
  'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterById' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
  'getClanById' : IDL.Func([IDL.Nat], [IDL.Opt(Clan)], ['query']),
  'getEpisodeById' : IDL.Func([IDL.Nat], [IDL.Opt(Episode)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
  'getGalleryItemById' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
  'getNewsPostById' : IDL.Func([IDL.Nat], [IDL.Opt(NewsPost)], ['query']),
  'getNewsPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(NewsPost)], ['query']),
  'getScriptById' : IDL.Func([IDL.Nat], [IDL.Opt(Script)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTeamMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
      ['query'],
    ),
  'removeMemberFromClan' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'reorderEpisodes' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'revokeRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCharacter' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Vec(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateClan' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateEpisode' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Nat),
        Visibility,
        IDL.Vec(IDL.Nat),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateGalleryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNewsPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateScript' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Visibility = IDL.Variant({
    'scheduled' : IDL.Null,
    'publicVisibility' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'clanId' : IDL.Opt(IDL.Nat),
    'episodes' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Clan = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Episode = IDL.Record({
    'id' : IDL.Nat,
    'taggedCharacterIds' : IDL.Vec(IDL.Nat),
    'writingComplete' : IDL.Bool,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'released' : IDL.Bool,
    'explicitReleaseDate' : IDL.Int,
    'animationComplete' : IDL.Bool,
    'voiceActingComplete' : IDL.Bool,
    'storyboardComplete' : IDL.Bool,
    'visibility' : Visibility,
    'videoUrl' : IDL.Text,
    'editingComplete' : IDL.Bool,
    'runtime' : IDL.Opt(IDL.Nat),
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const NewsPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Script = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemberToClan' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCharacter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'createClan' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createEpisode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Nat),
          Visibility,
          IDL.Vec(IDL.Nat),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'createGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createNewsPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createScript' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
    'deleteClan' : IDL.Func([IDL.Nat], [], []),
    'deleteEpisode' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteNewsPost' : IDL.Func([IDL.Nat], [], []),
    'deleteScript' : IDL.Func([IDL.Nat], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getAllClans' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
    'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterById' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
    'getClanById' : IDL.Func([IDL.Nat], [IDL.Opt(Clan)], ['query']),
    'getEpisodeById' : IDL.Func([IDL.Nat], [IDL.Opt(Episode)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
    'getGalleryItemById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(GalleryItem)],
        ['query'],
      ),
    'getNewsPostById' : IDL.Func([IDL.Nat], [IDL.Opt(NewsPost)], ['query']),
    'getNewsPostsByAuthor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsPost)],
        ['query'],
      ),
    'getScriptById' : IDL.Func([IDL.Nat], [IDL.Opt(Script)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTeamMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
        ['query'],
      ),
    'removeMemberFromClan' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'reorderEpisodes' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'revokeRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCharacter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateClan' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateEpisode' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Nat),
          Visibility,
          IDL.Vec(IDL.Nat),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateGalleryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNewsPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateScript' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };